package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TextblockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextblockAllPropertiesEquals(Textblock expected, Textblock actual) {
        assertTextblockAutoGeneratedPropertiesEquals(expected, actual);
        assertTextblockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextblockAllUpdatablePropertiesEquals(Textblock expected, Textblock actual) {
        assertTextblockUpdatableFieldsEquals(expected, actual);
        assertTextblockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextblockAutoGeneratedPropertiesEquals(Textblock expected, Textblock actual) {
        assertThat(actual)
            .as("Verify Textblock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextblockUpdatableFieldsEquals(Textblock expected, Textblock actual) {
        assertThat(actual)
            .as("Verify Textblock relevant properties")
            .satisfies(a -> assertThat(a.getDescriber()).as("check describer").isEqualTo(expected.getDescriber()))
            .satisfies(a -> assertThat(a.getNr()).as("check nr").isEqualTo(expected.getNr()))
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextblockUpdatableRelationshipsEquals(Textblock expected, Textblock actual) {
        assertThat(actual)
            .as("Verify Textblock relationships")
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
